# Generated by antigravity to fix .so issue.
import sys
import struct
import glob

def clear_execstack(path):
    with open(path, 'r+b') as f:
        magic = f.read(4)
        if magic != b'\x7fELF': return
        is_64bit = f.read(1) == b'\x02'
        f.seek(32 if is_64bit else 28)
        phoff = struct.unpack('<Q' if is_64bit else '<I', f.read(8 if is_64bit else 4))[0]
        f.seek(54 if is_64bit else 42)
        phentsize = struct.unpack('<H', f.read(2))[0]
        phnum = struct.unpack('<H', f.read(2))[0]
        for i in range(phnum):
            f.seek(phoff + i * phentsize)
            p_type = struct.unpack('<I', f.read(4))[0]
            if p_type == 0x6474e551:
                f.seek(phoff + i * phentsize + (4 if is_64bit else 24))
                flags = struct.unpack('<I', f.read(4))[0]
                if flags & 1:
                    flags &= ~1
                    f.seek(phoff + i * phentsize + (4 if is_64bit else 24))
                    f.write(struct.pack('<I', flags))
                    print(f"Cleared execstack for {path}")
                break

if __name__ == '__main__':
    for g in sys.argv[1:]:
        for p in glob.glob(g): clear_execstack(p)
